---
abstract: ~
author:
  - 'Brenda Wallace <shiny@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.68'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Net-Generatus
no_index:
  directory:
    - inc
    - t
requires:
  LWP::UserAgent: 2
  URI::Escape: 0
version: 0.31
