---
abstract: 'Get random status message from generatus.com'
author:
  - 'Brenda Wallace <shiny@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Generatus
no_index:
  directory:
    - inc
requires:
  LWP::UserAgent: 2
  URI::Escape: 0
version: 0.40
